import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import ClientProvider from "@/components/ClientProvider";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Warung",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased min-h-screen flex flex-col`}>
        <SessionProvider session={session}>
          <ClientProvider>
            <Toaster richColors position="bottom-right" />
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </ClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
